---
 - hosts: default
   sudo: yes
   vars: 
     - distro: debian
  
   roles:
     - ShadowKoBolt.core
     - ShadowKoBolt.ruby-simple
     - ShadowKoBolt.php5-common

   tasks:

     - name: set folder name variable
       set_fact:
         project_name: "drupal"

     - name: set Drupal Site name
       set_fact:
         site_name: "Sample Drupal site"

     - name: install bundle requirements
       apt: pkg={{ item }} state=present
       with_items:
         - libsqlite3-dev
         - libmysql-ruby
         - python-mysqldb
         - php5-xmlrpc
         - php5-memcache
         - memcached

     - name: bundle install
       remote_user: vagrant 
       sudo: no
       command: /home/vagrant/.gem/ruby/1.9.1/bin/bundle --binstubs chdir=/home/vagrant/source

     - name: setup mysql user
       mysql_user: name={{project_name}} password=password priv=*.*:ALL,GRANT  host=% state=present

     - name: set APPLICATION_ENV
       lineinfile: dest=/home/vagrant/.bashrc line="export APPLICATION_ENV=local" state=present regexp='^export APPLICATION_ENV='

     - name: create {{project_name}} db
       mysql_db: name={{project_name}} state=present login_user={{project_name}} login_password=password

     - name: install all composer packages
       command: php composer.phar install --no-interaction chdir=/home/vagrant/source

     - name: setup Drupal site through drush
       shell: yes 'y' | /home/vagrant/source/vendor/bin/drush site-install standard --db-url='mysql://{{project_name}}:password@localhost/{{project_name}}' --site-name={{site_name}} --account-name={{project_name}} --account-pass=password --account-mail={{project_name}}@{{project_name}}.com --site-mail={{project_name}}@{{project_name}}.com chdir=/home/vagrant/source/public/vagrant

     - name: copy vhost
       command: cp /home/vagrant/source/{{project_name}}_host /etc/apache2/sites-enabled/{{project_name}}

     - name: link vhost 
       file: src=/etc/apache2/sites-enabled/{{project_name}} dest=/etc/apache2/sites-available/{{project_name}} state=link

     - name: remove apache2 default host
       file: path=/etc/apache2/sites-enabled/000-default state=absent

     - name: remove apache2 default host
       file: path=/etc/apache2/sites-available/default state=absent

     - name: enable rewrite engine
       command: a2enmod rewrite
       sudo: yes

     - name: restart apache
       command: service apache2 restart
       sudo: yes

     - include: mailcatcher.yml 
